apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-lab
  namespace: argocd
spec:
  project: default
  sources:
      - repoURL: https://github.com/HiddenTechVillage/cks.git
        targetRevision: HEAD
        path: falco-lab/argocd/
        directory:
          recurse: true
  destination:
      server: https://kubernetes.default.svc
      namespace: default
  syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        selfHeal: true
        prune: true
