apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: attacker
  namespace: falco-lab
spec:
  project: default
  source:
      repoURL: https://github.com/HiddenTechVillage/cks.git
      targetRevision: HEAD
      path: falco-lab\attacker
  destination:
      server: https://kubernetes.default.svc
      namespace: default
  syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        selfHeal: true
        prune: true
