apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-lab
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: falco-lab
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 5.0.3
    helm:
      releaseName: falco-lab
      value: |
        falco:
          jsonOutput: true
          logLevel: info
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
